config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :celebrities do
    resources :reservations, only: [ :new, :create ]
    end
    resources :reservations, only: [ :show] do
      resources :reviews, only: [:create, :new]
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/pages/components', to: 'pages#components', as: :components
  get '/dashboard', to: 'dashboards#profile', as: :profile
  resources :reservations, only: [:show, :update, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/celebrity.rb
class Celebrity < ApplicationRecord

  belongs_to :user
  has_many :reservations
  has_one_attached :photo
  # debería existir la línea "has_many :reviews, through: :reservations"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_name_and_description,
    against: [ :first_name, :last_name, :description, :address ],
    using: {
      tsearch: { prefix: true }
    }

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  STATUS = %w(confirmed pending)
  belongs_to :user
  belongs_to :celebrity
  has_one :review, dependent: :destroy
  validates :reserve_begin, presence: true
  validates :reserve_end, presence: true
  validates :status, inclusion: { in: STATUS }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reservation
  validates :rating, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :celebrities, dependent: :destroy
  has_many :reservations, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit? --> see why this is not working properly


  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
  # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? ||
    params[:controller] =~ /(^(rails_)?admin)|(^pages$)/ ||
    params[:controller] == "dashboards" ||
    params[:controller] == "reservations" ||
    params[:controller] == "reviews"
  end
end

app/controllers/celebrities_controller.rb
class CelebritiesController < ApplicationController
  def index

    if params[:query].present?
      @celebrities = policy_scope(Celebrity).search_name_and_description(params[:query])
    else
      @celebrities = Celebrity.all
    end

    @markers = @celebrities.geocoded.map do |celebrity|
      {
        lat: celebrity.latitude,
        lng: celebrity.longitude
      }
    end
    authorize @celebrities
  end

  def show
    @celebrity = Celebrity.find(params[:id])
    @reservations = @celebrity.reservations
    authorize @celebrity
  end

  def new
    @celebrity = Celebrity.new
    authorize @celebrity
  end

  def create
    @celebrity = Celebrity.new(celebrity_params)
    @celebrity.user = current_user
    if @celebrity.save
      redirect_to profile_path
    else
      render :new
    end
    authorize @celebrity
  end

  def edit
    @celebrity = Celebrity.find(params[:id])
    authorize @celebrity
  end

  def update
    @celebrity = Celebrity.find(params[:id])
    @celebrity.update(celebrity_params)
    if @celebrity.save
      redirect_to celebrity_path(@celebrity)
    else
      render :new
    end
    authorize @celebrity
  end

  def destroy
    @celebrity = Celebrity.find(params[:id])
    @celebrity.destroy
    redirect_to profile_path
    authorize @celebrity
  end

  private

  def celebrity_params
    params.require(:celebrity).permit(:first_name, :last_name, :address, :description, :photo)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

def profile
@reservations = Reservation.all
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :components]
  def home
  end

  def components
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.new
    @celebrity = Celebrity.find(params[:celebrity_id])
  end


  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])

    if @reservation.update(reservation_params)
      redirect_to profile_path
    else
      render :dashboard
    end
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @celebrity = Celebrity.find(params[:celebrity_id])
    @reservation.status = "pending"
    @reservation.user = current_user
    @reservation.celebrity = @celebrity
      if @reservation.save!
        redirect_to reservation_path(@reservation)
      else
        render :new
      end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  private

  def reservation_params
    params.require(:reservation).permit(:reserve_begin, :reserve_end, :status, :celebrity_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @reservation = Reservation.find(params[:reservation_id])
  end

  def create
    @review = Review.new(review_params)
    @reservation = Reservation.find(params[:reservation_id])
    @review.reservation = @reservation
    if @review.save!
      redirect_to profile_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/celebrities/_form.html.erb
<div class="form_container">
  <h1 class="text-center">Create your celebrity here:</h1>
  <%= simple_form_for @celebrity do |f|%>
    <div class="form-group m-5 p-2">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group m-5 p-2">
      <%= f.label :last_name %>
      <%= f.text_area :last_name, class: 'form-control' %>
    </div>

    <div class="form-group m-5 p-2">
      <%= f.label :address %>
      <%= f.text_area :address, class: 'form-control' %>
    </div>

    <div class="form-group m-5 p-2">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group m-5 p-2">
      <%= f.label :photo %>
      <%= f.input :photo, as: :file, class: 'form-control' %>
    </div>


    <div class="d-flex justify-content-center mb-5">
      <%= f.submit class: 'button'%>
    </div>
  <% end %>
</div>

app/views/celebrities/edit.html.erb
<%= render 'form', task: @celebrity %>

<%= link_to celebrities_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/celebrities/index.html.erb
<div class="margin-top">

  <div class="col-6">

    <div class="container">

      <h1 class="text-center mb-3" id="logo-font">Choose your favourite celebrity</h1>

      <div class="search-bar mb-3 mt-4">

        <div class="searchbar-form">
          <%= form_tag celebrities_path, method: :get do %>
            <%= text_field_tag :query, params[:query], class: "form-control be-0" %>
            <%= submit_tag "Search", class: "map-button border-0 rounded-left" %>
          <% end %>
        </div>
      </div>
      <%= render 'shared/card_celebrity', collection: @celebrities %>
    </div>
  </div>

  <div class="map-wrapper col-6">
    <div id="map"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
       style="height: 100vh; position: sticky; top: 0; width: 100%;">
    </div>
  </div>

</div>

app/views/celebrities/new.html.erb
<%= render 'shared/form' %>

app/views/celebrities/show.html.erb
<div class="celebrity-photo d-flex">
  <a><%= cl_image_tag @celebrity.photo.key, height: 300, width: 400, crop: :fill %></a>
</div>

<div class="celebrity-description">
  <h1 class="mb-5"><%=@celebrity.first_name%> <%=@celebrity.last_name%></h1>
  <p><%=@celebrity.address %></p>
  <p class="text-justify"><%= @celebrity.description %></p>
  
  <% if policy(@celebrity).edit? == false %>
  <button class="button text-center text-white ml-0">
    <%= link_to 'Book now', new_celebrity_reservation_path(@celebrity), class: "text-white" %>
  </button>
  <% end %>
  
  <% if policy(@celebrity).edit? %>
  <button class="button text-center text-white ml-0">
    <%= link_to 'Edit', edit_celebrity_path, class: "text-white" %>
  </button>
  <% end %>
  
  <% if policy(@celebrity).destroy? %>
  <button class="button text-center text-white ml-0">
    <%= link_to 'Delete', celebrity_path(@celebrity), method: :delete, data: { confirm: "Proceed?" },  class: "text-white" %>
  </button>
  <% end %>
  
</div>
</div>

<h2 class="review-show-celebrity">Reviews</h2>
<div class="reservations-in-show-celebrity">
  <% @reservations.each do |reservation| %>
  <div class="d-flex">
    <ul class="stars-for-show-celebrity">
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="far fa-star"></i>
    </ul>
    <p class="pl-4 text-muted"> <%= reservation&.created_at.strftime("%m/%d/%Y") %></p>
  </div>
  
  <div class="pl-3">
    <p class="pl-4"> <%= reservation&.review&.content %></p>
  </div>
  
  <div class="d-flex mb-5">
    <i class="far fa-thumbs-up pl-5"></i>
    <p class="pl-4 text-muted">Like</p>
  </div>
  <% end %>
</div>

<div class="d-flex justify-content-center m-5">
  <button class="button text-center text-white">
    <%= link_to 'See all celebrities', celebrities_path, class: "text-white" %>
  </button>
</div>

app/views/dashboards/profile.html.erb
<div class="pt-5 mt-5 mycontainer">
  <div class="d-flex">
    <div class="card celebrity-photo-show sidebar col-3" style="width: 35rem;">
      <div class="card-body">
        <h5><%= current_user.first_name.capitalize  %> <%= current_user.last_name.capitalize  %></h5>
      </div>
      <div >
        <a href="#" class="card-link"><%= link_to "New Celebrity", new_celebrity_path, class:'button' %></a>
      </div>
      <div >
        <a href="#" class="card-link"><a href="#reservation" class="button"> Reservations</a>
      </div>
      <div >
        <a href="#" class="card-link"><a href="#celebrities" class="button"> My celebrities</a>
      </div>
      <div >
        <a href="#" class="card-link"><%= link_to "Find you celebrity now", celebrities_path, class:'button' %></a>
      </div>
    </div>

    <div class="col-9">
      <div class="dashboard-content">
        <h1>Hello <%= current_user.first_name.capitalize%>! These are your reservations:</h1>
        <% if current_user.reservations.empty? %>
        <p> You do not have any reservation yet... </p>
        <% else %>
        <div class="cards">
          <% if current_user.reservations %>
            <% current_user.reservations.each do |reservation| %>
            <div class="card-container">
              <div class="card-body">
                <div class="card-celebrity-body">
                  <div>
                    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path reservation.celebrity.photo.key, crop: :fill, gravity: :face %>')">
                    </div>
                    <p class="text-center logo-font my-1"><strong> <%= reservation.celebrity.first_name %> <%= reservation.celebrity.last_name %></strong></p>
                    <p class="text-center logo-font my-1"><strong>From:</strong>  <%= reservation.reserve_begin%></p>
                    <p class="text-center logo-font my-1"><strong> To: </strong> <%= reservation.reserve_end%></p>
                    <p class="text-center logo-font my-1"> <strong>Status: </strong><%= reservation.status.capitalize %></p>
                    <!-- <p class="text-center my-1"><%#= link_to "Update Reservation", edit_reservation_path(reservation) %></p> -->
                  </div>
                </div>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
        <% end %>

        <div>
          <% if current_user.celebrities.blank?  %>
          <p class="text-center mb-5" id="logo-font">You do not have any celebrity yet...</p>
          <p></p>
          <%= link_to "Create celebrity", new_celebrity_path, class:'button' %>
          <%  else %>
          <p class="text-center mb-5" id="logo-font">These are your celebrities</p>
          <div class="cards" id="celebrities">
            <% if current_user.celebrities %>
              <% current_user.celebrities.each do |celebrity| %>
              <%= link_to celebrity_path(celebrity.id), class: "no-deco" do %>
              <div class="celebrity-conteiner">
                <div class="card-celebrity-body">
                  <div>
                    <div class="card-celebrity" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path celebrity.photo.key, crop: :fill, gravity: :face %>')"></div>
                    <p class="text-center logo-font my-1 no-deco"><%= "#{celebrity.first_name} #{celebrity.last_name}" %></p>
                    <p class="text-center my-1 no-deco">150€/hour</p>
                    <ul class="stars">
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                      <i class="far fa-star"></i>
                    </ul>
                  </div>
                </div>
              </div>
              <% end %>
            <% end %>
          <% end %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeFamousToo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render '/shared/navbar' %>
    <%= render '/shared/flashes' %>

    <%= yield %>

    <%= render '/shared/footer' %>
  </body>
</html>

app/views/pages/components.html.erb
<div class="banner">
  <h1 id="logo-font">Don't dream with meeting a famous</h1>
  <p>Rent your celebrities here!</p>
  <div class="p-3">
    <a class="button p-3" id="logo-font-w" href="#">This is a button</a>
  </div>
</div>

<div class="mycontainer col-8 p-3 my-3">
  <%= render '/shared/card-seller-1' %>
  <%= render '/shared/card-seller-2' %>
</div>

<%= render '/shared/card_celebrity' %>

app/views/pages/home.html.erb
<div class="banner">
  <h1 id="logo-font">Make your dreams come true</h1>
  <p>Get to meet your idol!</p>
  <div class="search p-3">
    <%= link_to "Search", celebrities_path, class: "button", id: "logo-font-w"%>
  </div>
</div>

<div class="mycontainer p-3 my-3">
  <%= render 'shared/card-seller-1'  %>
  <!-- <div class="homepage-container">
    <div class="card-title">
      <h2>Your celebrities</h2>
    </div>
    <div class="celebrity-conteiner mb-3">
      <div class="card-celebrity-body">
        <div class="image-hover">
          <div class="card-celebrity" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.hola.com/imagenes/biografias/michael-jackson/79629-jackson10.jpg)"></div>
          <p class="text-center logo-font my-1">Michael Jackson</p>
          <p class="text-center my-1">150€/hour</p>
          <ul class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
            <i class="far fa-star"></i>
          </ul>
        </div>
      </div>

      <div class="card-celebrity-body">
        <div class="image-hover">
          <div class="card-celebrity" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://pbs.twimg.com/profile_images/1332098013511213058/JaZeyYKd_400x400.jpg)"></div>
          <p class="text-center logo-font my-1">Miley Cirus</p>
          <p class="text-center my-1">200€/hour</p>
          <ul class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
          </ul>
        </div>
      </div>

      <div class="card-celebrity-body">
        <div class="image-hover">
          <div class="card-celebrity" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://jenesaispop.com/wp-content/uploads/2020/06/bjork-post.jpg"></div>
          <p class="text-center logo-font my-1">Björk</p>
          <p class="text-center my-1">270€/hour</p>
          <ul class="stars">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          </ul>
        </div>
      </div>
    </div> -->
  </div>
  <div class="search button-wrapper" style="display:flex; justify-content: center;" >
    <%= link_to "See all", celebrities_path, class: "button", style:"width: 250px;"%>
  </div>

</div>

app/views/reservations/_form.html.erb
<div class="form_container">
  <h1 class="text-center">When would you like to book? </h1>
  <%= simple_form_for [ @celebrity, @reservation ] do |f| %>
    <div class="form-group m-5 p-2">
      <%= f.input :reserve_begin %>
    </div>
    <div class="form-group m-5 p-2">
      <%= f.input :reserve_end %>
    </div>
    <div class="d-flex justify-content-center mb-5">
      <%= f.submit "Book Now",class: 'btn button' %>
    </div>
  <% end %>
</div>

app/views/reservations/edit.html.erb
<div class="form_container">
  <h1 class="text-center">Cancel o approve your reservation here:</h1>
  <%= simple_form_for [ @celebrity, @reservation ] do |f| %>
  <div class="form-group m-5 p-2">
    <%= f.input :status, collection: Reservation::STATUS %>
  </div>
</div>
<div class="d-flex justify-content-center mb-5">
  <%= f.submit "Submit reservation",class: 'btn button' %>
</div>
<% end %>

app/views/reservations/new.html.erb
<%= render 'form', task: @reservation %>

app/views/reservations/show.html.erb
<div class="celebrity-photo d-flex">
  <div class="celebrity-photo-show" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.5)), url('<%= cl_image_path @reservation.celebrity.photo_url, crop: :fill, gravity: :face %>');">
  </div>

  <div class="celebrity-description">
    <h1>Your Reservation:</h1>
    <h2><%=@reservation.celebrity.first_name %> <%=@reservation.celebrity.last_name %></h2>
    <p>From: <%=@reservation.reserve_begin%></p>
    <p>To: <%=@reservation.reserve_end%></p>
    <p><strong>Status: </strong><%=@reservation.status.capitalize %></p>
    <% if @reservation.status == 'confirmed'%>
      <%= link_to "Write a review", new_reservation_review_path(@reservation) %>
    <% end %>
     </p>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="form_container">
  <h1 class="text-center">How was your experience?</h1>
  <div class="container ml-5">



    <%= simple_form_for [@reservation, @review] do |f|%>


      <div class="form-group m-5 p-2">
        <%= f.label :content %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <div class="form-group m-5 p-2">
        <%= f.input :rating, collection: 1..5 %>
      </div>

<%= f.submit class: 'button'%>

<% end %>
</div>


</div>

app/views/shared/_card-seller-1.html.erb
  <div class="card-container">
    <div class="card-title pt-2">
      <h2>Most rented celebrities</h2>
    </div>

    <div class="card-body">
      <div>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.hola.com/imagenes/biografias/michael-jackson/79629-jackson10.jpg)"></div>
        <p class="text-center logo-font my-1">Michael Jackson</p>
        <p class="text-center my-1">200€/hour</p>
        <ul class="stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="far fa-star"></i>
          <i class="far fa-star"></i>
          <i class="far fa-star"></i>
        </ul>
      </div>

      <div>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.cinconoticias.com/wp-content/uploads/jimi-hendrix-1068x575.jpg)"></div>
        <p class="text-center logo-font my-1">Jimmy Hendrix</p>
        <p class="text-center my-1">340€/hour</p>
        <ul class="stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="far fa-star"></i>
        </ul>
      </div>

      <div>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://64.media.tumblr.com/8bb48c4cc0f0c181c8de2991cd590a13/tumblr_pm62y5MvN91rj7g0yo1_500.png)"></div>
        <p class="text-center logo-font my-1">Amy Winehouse</p>
        <p class="text-center my-1">550€/hour</p>
        <ul class="stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="far fa-star"></i>
          <i class="far fa-star"></i>
        </ul>
      </div>
    </div>
  </div>

app/views/shared/_card-seller-2.html.erb
  <div class="card-container">
    <div class="card-title pt-2">
      <h3>Celebrities near you</h3>
    </div>

    <div class="card-body">
      <div>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://okdiario.com/img/2017/12/28/quien-fue-elvis-presley-el-rey-del-rock-and-roll-2-655x368.jpg)"></div>
        <p class="text-center logo-font my-1">Michael Jackson</p>
        <p class="text-center my-1">200€/hour</p>
        <ul class="stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="far fa-star"></i>
          <i class="far fa-star"></i>
          <i class="far fa-star"></i>
        </ul>
      </div>

      <div>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.hola.com/imagenes/biografias/michael-jackson/79629-jackson10.jpg)"></div>
        <p class="text-center logo-font my-1">Michael Jackson</p>
        <p class="text-center my-1">200€/hour</p>
         <ul class="stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="far fa-star"></i>
          <i class="far fa-star"></i>
          <i class="far fa-star"></i>
      </ul>
      </div>

      <div>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i0.wp.com/www.mexmads.com/wp-content/uploads/2020/05/ariana-grande-interpuso-orden-alejamiento_0_21_705_437.jpg?resize=958%2C596)"></div>
        <p class="text-center logo-font my-1">Michael Jackson</p>
        <p class="text-center my-1">200€/hour</p>
        <ul class="stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
       </ul>
      </div>
    </div>
  </div>

app/views/shared/_card_celebrity.html.erb
<div class="cards-index">
  <% @celebrities.each do |celebrity| %>
    <%= link_to celebrity_path(celebrity.id), class: "no-deco" do %>
      <div class="celebrity-conteiner">
        <div class="card-celebrity-body">
          <div>
            <a><%= cl_image_tag celebrity.photo.key, height: 300, width: 400, crop: :fill %></a>
            <p class="text-center logo-font my-1 no-deco"><%= "#{celebrity.first_name} #{celebrity.last_name}" %></p>
            <p class="text-center my-1 no-deco">150€/hour</p>
            <ul class="stars">
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="far fa-star"></i>
              <i class="far fa-star"></i>
              <i class="far fa-star"></i>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Contact us! <i class="fas fa-heart"></i>
  </div>
</div>